export const LIST_FEED_REQUEST = 'LIST_FEED_REQUEST';
export const LIST_FEED_SUCCESS = 'LIST_FEED_SUCCESS';
export const LIST_FEED_FAILURE = 'LIST_FEED_FAILURE';
export const LIST_FEED_IDLE = 'LIST_FEED_IDLE';
