version: 2.1
jobs:
  node:
    working_directory: ~/repo
    docker:
      - image: cimg/node:15.3.0

    steps:
      - checkout

      - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "package.json" }}
                  - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
      
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
        
  android-alpha:
    working_directory: ~/boilerplate/android
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout:
          path: ~/boilerplate

      - attach_workspace:
          at: ~/repo

      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run: bundle install

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: fastlane android alpha
          command: |
            bundle exec fastlane alpha

      - store_artifacts:
          path: android/app/build/outputs/apk/release/app-release.apk

  android-beta:
    working_directory: ~/boilerplate/android
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout:
          path: ~/boilerplate

      - attach_workspace:
          at: ~/repo

      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run: bundle install

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: fastlane android beta
          command: |
            bundle exec fastlane beta

  ios-beta:
    working_directory: ~/boilerplate/ios
    macos:
      xcode: 12.5.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test

    steps:
      - checkout
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - ~/.cache/npm

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - restore_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}

      #Pods directory is ignored to match default RN setup, but can also check them into source control
      #https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control
      - restore_cache:
          key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}

      - run: 
          command: pod install
          working_directory: ios

      - run: 
          command: bundle install
          working_directory: ios

      - save_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - save_cache:
          key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}
          paths:
            - ios/Pods

      - run:
          name: Fastlane
          command: bundle exec fastlane beta
          working_directory: ios

  ios-prod:
    working_directory: ~/boilerplate/ios
    macos:
      xcode: 12.5.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test

    steps:
      - checkout
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - ~/.cache/npm

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - restore_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}

      #Pods directory is ignored to match default RN setup, but can also check them into source control
      #https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control
      - restore_cache:
          key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}

      - run: 
          command: pod install
          working_directory: ios

      - run: 
          command: bundle install
          working_directory: ios

      - save_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - save_cache:
          key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}
          paths:
            - ios/Pods

      - run:
          name: Fastlane
          command: bundle exec fastlane prod
          working_directory: ios
workflows:
  node-android-ios:
    jobs:
      - android-hold: 
          type: approval
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - ios-hold:
          type: approval
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - node:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - android-alpha:
          requires:
            - node
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - android-beta:
          requires:
            - android-hold
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - ios-beta:
          requires:
            - node
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - ios-prod:
          requires:
            - ios-hold 
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/      