# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :alpha do
    gradle(task: "clean assembleRelease")
  end
  lane :gitpush do
    # Get the last version code and increment it.
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/ 

    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close
    # Code Ended.
    git_add
    git_commit(path: "*", message: "Android Version Incremented.")
    push_to_git_remote
  end
  lane :beta do
    gradle(task: "clean assembleRelease")
  end
end
