# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  lane :beta do
    increment_build_number(xcodeproj: "boilerplate.xcodeproj")
    build_app(workspace: "boilerplate.xcworkspace", scheme: "boilerplate", export_method: "development", silent: "true", output_directory: "./build_ipa")
  end]